In [3]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier

In [2]:
X_train = pd.read_csv('data/train2.csv')
X_test = pd.read_csv('data/test2.csv')

y_train = X_train['Survived']
y_train = np.asarray(y_train)

ID_train = X_train['PassengerId']
ID_train = np.asarray(ID_train)

X_train = X_train.drop(columns=['PassengerId', 'Survived'])
X_train = np.asarray(X_train)

ID_test = X_test['PassengerId']
ID_test = np.asarray(ID_test)

X_test = X_test.drop(columns=['PassengerId'])
X_test = np.asarray(X_test)

In [5]:
print(X_train)

[[1.         1.         0.27117366 ... 0.         0.01415106 0.66666667]
 [0.         0.         0.4722292  ... 0.         0.13913574 0.        ]
 [1.         0.         0.32143755 ... 0.         0.01546857 0.66666667]
 ...
 [1.         0.                nan ... 0.33333333 0.04577135 0.66666667]
 [0.         1.         0.32143755 ... 0.         0.0585561  0.        ]
 [1.         1.         0.39683338 ... 0.         0.01512699 0.33333333]]


In [9]:
col_mean_train = np.nanmean(X_train, axis=0)
print(col_mean_train)

col_mean_test = np.nanmean(X_test, axis=0)
print(col_mean_test)

[0.65432099 0.64758698 0.36792055 0.06537598 0.06359895 0.06285843
 0.51290685]
[0.63277512 0.63636364 0.39697468 0.05592105 0.04359383 0.06953964
 0.70095694]


In [10]:
inds_train = np.where(np.isnan(X_train))
X_train[inds_train] = np.take(col_mean_train, inds_train[1])

inds_test = np.where(np.isnan(X_test))
X_test[inds_test] = np.take(col_mean_test, inds_test[1])

In [11]:
mlp_model = MLPClassifier(hidden_layer_sizes=(150,100,50), activation='relu')
mlp_model.fit(X_train, y_train)

y_pred_mlp = mlp_model.predict(X_test)

In [12]:
results = pd.DataFrame()
results['PassengerId'] = ID_test
results['Survived'] = y_pred_mlp

results.to_csv(r'data/results1.csv', index=False)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

In [14]:
results2 = pd.DataFrame()
results2['PassengerId'] = ID_test
results2['Survived'] = y_pred_knn

results.to_csv(r'data/results2.csv', index=False)